on:
  pull_request:
  merge_group:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: cargo test --workspace --no-fail-fast
      - run: cargo clippy --workspace -- --deny warnings
